export const SHOW_LOADING = "SHOW_LOADING";
export const HIDE_LOADING = "HIDE_LOADING";


export const LOGIN_SUCCESS = "LOGIN_SUCCESS"; 
export const LOGIN_FAILED = "LOGIN_FAILED" ;

export const USER_WITH_TOKEN_SUCCESS = "USER_WITH_TOKEN_SUCCESS";
export const USER_WITH_TOKEN_FAILED = "USER_WITH_TOKEN_FAILED";

export const LOG_OUT = "LOG_OUT";

export const GET_MUSIC_STORE_SUCCESS = "GET_MUSIC_STORE_SUCCESS";
export const GET_MUSIC_STORE_FAILED = "GET_MUSIC_STORE_FAILED";

export const SORT_ASC = "SORT_ASC";
export const SORT_DESC = "SORT_DESC"; 

export const FILTER_BY_GENRE = "FILTER_BY_GENRE";

export const MUSIC_STORE_CHANGED = "MUSIC_STORE_CHANGED"